### ISSUE TITLE
iPlayer throwing exception when trying to open stream on Kodi 15.0-RC1

### ISSUE THREAD

**Issue by greve** [joolswills/plugin.video.iplayer#167]
On Intel NUC, running

Kodi (15.0-RC1 Git:2015-06-19-1d20e72). Platform: Linux x86 64-bit
Using Debug Kodi x64 build
Kodi compiled Jun 19 2015 by GCC 4.8.3 for Linux x86 64-bit version 3.10.0 (199168)
Running on CentOS Linux 7 (Core), kernel: Linux x86 64-bit version 3.10.0-229.4.2.el7.x86_64
FFmpeg statically linked, version: 2.6.2-kodi-2.6.2-Isengard-beta
Host CPU: Intel(R) Core(TM) i3-4010U CPU @ 1.70GHz, 4 cores available

with iPlayer-v2.7.1.zip installed, attempting to open any stream results in immediate crash of plugin:

21:39:39 T:139866952169216    INFO: plugin.video.iplayer: URL Fetch took 0.02 sec for http://www.bbc.co.uk/iplayer/playlist/b00t4lqf
21:39:39 T:139866952169216  NOTICE: Traceback (most recent call last):
21:39:39 T:139866952169216  NOTICE:   File "/home/guest/.kodi/addons/plugin.video.iplayer/default.py", line 955, in <module>
21:39:39 T:139866952169216  NOTICE:     watch(feed, pid)
21:39:39 T:139866952169216  NOTICE:   File "/home/guest/.kodi/addons/plugin.video.iplayer/default.py", line 783, in watch
21:39:39 T:139866952169216  NOTICE:     item      = iplayer.programme(pid).programme
21:39:39 T:139866952169216  NOTICE:   File "/home/guest/.kodi/addons/plugin.video.iplayer/lib/iplayer2.py", line 764, in programme
21:39:39 T:139866952169216  NOTICE:     for i in self.items:
21:39:39 T:139866952169216  NOTICE:   File "/home/guest/.kodi/addons/plugin.video.iplayer/lib/iplayer2.py", line 59, in result
21:39:39 T:139866952169216  NOTICE:     loader(self)
21:39:39 T:139866952169216  NOTICE:   File "/home/guest/.kodi/addons/plugin.video.iplayer/lib/iplayer2.py", line 52, in result
21:39:39 T:139866952169216  NOTICE:     fn(self)
21:39:39 T:139866952169216  NOTICE:   File "/home/guest/.kodi/addons/plugin.video.iplayer/lib/iplayer2.py", line 673, in read_playlist
21:39:39 T:139866952169216  NOTICE:     self.parse_playlist(self.playlist)
21:39:39 T:139866952169216  NOTICE:   File "/home/guest/.kodi/addons/plugin.video.iplayer/lib/iplayer2.py", line 687, in parse_playlist
21:39:39 T:139866952169216  NOTICE:     tree = ET.XML(xmlstr)
21:39:39 T:139866952169216  NOTICE:   File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1300, in XML
21:39:39 T:139866952169216  NOTICE:     parser.feed(text)
21:39:39 T:139866952169216  NOTICE:   File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
21:39:39 T:139866952169216  NOTICE:     self._raiseerror(v)
21:39:39 T:139866952169216  NOTICE:   File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
21:39:39 T:139866952169216  NOTICE:     raise err
21:39:39 T:139866952169216  NOTICE: ParseError: syntax error: line 1, column 49
21:39:39 T:139866952169216   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'xml.etree.ElementTree.ParseError'>
                                            Error Contents: syntax error: line 1, column 49
                                            Traceback (most recent call last):
                                              File "/home/guest/.kodi/addons/plugin.video.iplayer/default.py", line 955, in <module>
                                                watch(feed, pid)
                                              File "/home/guest/.kodi/addons/plugin.video.iplayer/default.py", line 783, in watch
                                                item      = iplayer.programme(pid).programme
                                              File "/home/guest/.kodi/addons/plugin.video.iplayer/lib/iplayer2.py", line 764, in programme
                                                for i in self.items:
                                              File "/home/guest/.kodi/addons/plugin.video.iplayer/lib/iplayer2.py", line 59, in result
                                                loader(self)
                                              File "/home/guest/.kodi/addons/plugin.video.iplayer/lib/iplayer2.py", line 52, in result
                                                fn(self)
                                              File "/home/guest/.kodi/addons/plugin.video.iplayer/lib/iplayer2.py", line 673, in read_playlist
                                                self.parse_playlist(self.playlist)
                                              File "/home/guest/.kodi/addons/plugin.video.iplayer/lib/iplayer2.py", line 687, in parse_playlist
                                                tree = ET.XML(xmlstr)
                                              File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1300, in XML
                                                parser.feed(text)
                                              File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
                                                self._raiseerror(v)
                                              File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
                                                raise err
                                            ParseError: syntax error: line 1, column 49
                                            -->End of Python script error report<--

**Comment by joolswills** [comment]
BBC killed off our stream sources. Plugin is dead. See the iplayer thread on the kodi forum for more details

**Comment by greve** [comment]
Meh. Bastards. :-/
