### ISSUE TITLE
Live stream video jitter on Raspberry Pi 2

### ISSUE THREAD

**Issue by jdalleniii** [joolswills/plugin.video.iplayer#170]
I am experiencing jitter in the video output when switching to a live stream playing on a Raspberry Pi 2. It sometimes settles down after 20 minutes, sometimes much longer than that.

Here are a couple of videos that demonstrate the issue:
https://youtu.be/P1Wq2TOYNms
https://youtu.be/DZhUDHxQt58

The scrolling text at the end of the second video is perhaps the clearest illustration of the problem.

It's probably worth noting that I have two identical Pi installations that behave in exactly the same way, and a Macbook installation that works fine from the outset.

**Comment by joolswills** [comment]
This plugin is broken and no longer in development - your issue must be with one of the other iplayer plugins. Also the plugins won't be able to fix the issue you mention as they just send urls to Kodi to play.
